apiVersion: v1
kind: Pod
metadata:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-seguridad-app
      image: ivanimg20/securityapiservice
      ports:
        - containerPort: 80
      env:
        - name: ConnectionStrings__ConexionDb
          value: Server=mssql-service;Database=Seguridad;User=sa;Password=$7432Img#2022