apiVersion: apps/1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    name: mongo-deploy
    app: microservice-libreria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-libreria
      name: mongo-pod
  template:
    metadata:
      name: mongo-pod
      labels:
        app: microservice-libreria
        name: mongo-pod
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.21
          command:
            - /bin/bash
            - -c
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "ivanmtz"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "$7432Img#2022"
          ports:
            - containerPort: 27017